# Generated by Django 5.1.4 on 2026-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('camera', 'Câmera'), ('biometria', 'Biometria'), ('central_alarme', 'Central de Alarme')], default='camera', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('nvr', 'NVR'), ('dvr', 'DVR'), ('rack', 'Rack')], default='nvr', max_length=20),
        ),
    ]
