# Generated by Django 5.1.4 on 2026-05-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0002_alter_floor_options_equipment_type_alter_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='condominiums.device'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='condominiums.equipment'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('executing', 'Executando'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
    ]
