# Generated by Django 5.1.4 on 2026-05-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0003_maintenance_device_maintenance_equipment_and_more'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='technicians.technician'),
        ),
    ]
