# Generated by Django 5.1.4 on 2026-05-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0004_maintenance_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='device',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='equipment',
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_items', to='condominiums.device')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_items', to='condominiums.equipment')),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='condominiums.maintenance')),
            ],
            options={
                'db_table': 'maintenance_items',
            },
        ),
    ]
