# Generated by Django 5.1.4 on 2026-05-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0005_remove_maintenance_device_and_more'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='condominiums.condominium')),
                ('maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='condominiums.maintenance')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='technicians.technician')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
